services:
  postgres:
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_DB: transfer_track
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5432:5432'